version: "3"
services:

  # Zookeeper 서비스 설정 (Kafka의 의존성)
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  # Kafka 서비스 설정
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "chatting:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # 웹 서버 (nginx) 설정
  web:
    image: nginx
    container_name: web
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - spring

  # MySQL 데이터베이스 서비스 설정
  chatting-mysql:
    image: "mysql:8.0"
    container_name: "chatting-mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dnduf4594
      MYSQL_DATABASE: chatting_db
    volumes:
      - mysql_data:/var/lib/mysql

  # Spring Boot 애플리케이션 설정
  spring:
    build: .
    container_name: chatting
    ports:
      - "8080:8080"
    depends_on:
      - chatting-mysql
      - kafka

# 서비스들이 연결될 네트워크 설정
networks:
  chatting-network:
    driver: bridge

# 데이터베이스 데이터를 위한 볼륨 설정
volumes:
  mysql_data:
